---
layout: post
title:  "一些小问题解决"
date:   2017-05-07 20:00:03 +0800
categories: jekyll update
tags: Java
---



最近一段时间堕落了。 = = 



买了个PS4，天天晚上回家就玩游戏去了。 = = 



这篇以后用来记录一些小问题吧。



---



### MySQL 驱动版本不对 导致数据库bit类型字段异常



```java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at com.mysql.cj.mysqla.MysqlaUtils.bitToLong(MysqlaUtils.java:68)
	at com.mysql.cj.core.io.MysqlTextValueDecoder.decodeBit(MysqlTextValueDecoder.java:231)
	at com.mysql.cj.jdbc.ResultSetRow.decodeAndCreateReturnValue(ResultSetRow.java:170)
	at com.mysql.cj.jdbc.ResultSetRow.getValueFromBytes(ResultSetRow.java:269)
	at com.mysql.cj.jdbc.BufferRow.getValue(BufferRow.java:349)
	at com.mysql.cj.jdbc.ResultSetImpl.getNonStringValueFromRow(ResultSetImpl.java:813)
	at com.mysql.cj.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:904)
	at com.mysql.cj.jdbc.ResultSetImpl.getBoolean(ResultSetImpl.java:908)
```

[https://bugs.mysql.com/bug.php?id=81755](https://bugs.mysql.com/bug.php?id=81755)



---



### MyBatis 查询返回插入后主键的值



单个的insert语句 加个selectkey标签



```xml
    <insert id="insert" parameterType="mbxc.task.domain.TaskGroup">
        insert into task_group
        <trim prefix="(" suffix=")" suffixOverrides=",">
            `id`,
            `nick`,
            `type`,
            `field`,
        </trim>
        <trim prefix="values (" suffix=")" suffixOverrides=",">
            #{id,jdbcType=BIGINT},
            #{nick,jdbcType=VARCHAR},
            #{type,jdbcType=VARCHAR},
            #{field,jdbcType=CHAR},
        </trim>
        <selectKey resultType="java.lang.Long" keyProperty="id">
            SELECT @@IDENTITY AS id
        </selectKey>
    </insert>
```



批量插入返回主键值 在 ``mybatis3.3.1`` 就已经支持了 

[https://github.com/mybatis/mybatis-3/pull/547](https://github.com/mybatis/mybatis-3/pull/547)

```xml
    <insert id="insertBatch" useGeneratedKeys="true" keyProperty="id" keyColumn="id">
        insert into task
        (
        `params`,
        `status`,
        `exit_code`,
        `group_id`,
        `message`,
        `date_created`,
        `last_updated`
        ) values
        <foreach collection="list" item="item" index="index" separator=" , ">
            (
            #{item.params,jdbcType=LONGVARCHAR},
            #{item.status,jdbcType=CHAR},
            #{item.exitCode,jdbcType=CHAR},
            #{item.groupId,jdbcType=BIGINT},
            #{item.message,jdbcType=LONGVARCHAR},
            #{item.dateCreated,jdbcType=TIMESTAMP},
            #{item.lastUpdated,jdbcType=TIMESTAMP})
        </foreach>
    </insert>
```



---



### 服务报出Broken pipe 异常奔溃



有天凌晨一个重要的服务突然宕机了。

看**gray2log**日志打印的是``java-io-ioexception-broken-pipe``。



```java
org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe	
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:389)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:426)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:338)
	at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:291)
	at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:151)
	at org.apache.struts2.dispatcher.StreamResult.doExecute(StreamResult.java:305)
	at org.apache.struts2.dispatcher.StrutsResultSupport.execute(StrutsResultSupport.java:186)
	at com.opensymphony.xwork2.DefaultActionInvocation.executeResult(DefaultActionInvocation.java:371)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:275)
	at org.apache.struts2.interceptor.DeprecationInterceptor.intercept(DeprecationInterceptor.java:41)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at org.apache.struts2.interceptor.debugging.DebuggingInterceptor.intercept(DebuggingInterceptor.java:256)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
	at com.opensymphony.xwork2.interceptor.DefaultWorkflowInterceptor.doIntercept(DefaultWorkflowInterceptor.java:167)
	at com.opensymphony.xwork2.interceptor.MethodFilterInterceptor.intercept(MethodFilterInterceptor.java:98)
	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:246)
```



测试的时候都很正常，最近的更新也确定不会引发这个问题。

突然想起之前有一次部署的服务也出现过这个问题，原因是数据库地址是测试库的。

最后发现是获取数据库链接时候获取不到造成的。询问服务商回答说最近机房网络环境不稳定线路在做整改。。。



---



### 启动项目成功后又shutdown



接手同事一个项目，要进行功能上的迭代

```java
2017-05-07 21:18:52.696  INFO 17475 --- [           main] mbxc.ShowcaseScheduleApplication         : Started ShowcaseScheduleApplication in 27.189 seconds (JVM running for 27.977)
2017-05-07 21:18:52.697  INFO 17475 --- [       Thread-3] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@7dfd3c81: startup date [Sun May 07 21:18:46 CST 2017]; root of context hierarchy
2017-05-07 21:18:52.700  INFO 17475 --- [       Thread-3] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 0
2017-05-07 21:18:52.702  INFO 17475 --- [       Thread-3] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
2017-05-07 21:18:52.703  INFO 17475 --- [       Thread-3] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
```



然后报了这个异常。。  查来查去没发现啥毛病。 Google也没有确切的答案。

然后突然看到 配置类上面的注解     **@Profile("product")**

知道了。。  我本地的**application.properties** 并没有指定 **spring.profiles.active**

加载有 **@Configuration** 这个注解的类就相当于是空的。



---









